# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f99b070bef6dec2b4386313ebe0af234"
name = "Velto"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
automatically_update_urls_on_dev = true
