name = "Velto"
application_url = "https://mini-somewhere-ordered-treatment.trycloudflare.com"
embedded = true
client_id = "f99b07bef6dec2b438613ebe0af234"

[webhooks]
api_version = "2026-07"

[[webhooks.subscriptions]]
uri = "/webhooks/gdpr"
compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access_scopes]
scopes = "read_discounts,read_orders,read_products,write_discounts,write_orders,write_products"

[auth]
redirect_urls = [ "https://mini-somewhere-ordered-treatment.trycloudflare.com/api/auth" ]

[build]
automatically_update_urls_on_dev = true
